version: 2
#formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
python:
  # For available versions, see:
  # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-image
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
