# -*- coding:utf-8 -*-
# /usr/bin/env python
"""
Date: 2021/1/13 17:16
Desc: 新浪财经-股票-行业分类

"""
import requests
import pandas as pd

url = "http://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodes"
r = requests.get(url)
data_json = r.json()
temp_df = pd.DataFrame(data_json[1][0][1][0][1])
temp_df

headers = {
    'accept': 'application/json, text/javascript, */*; q=0.01',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'referer': 'https://www.thebankerdatabase.com/index.cfm/search/ranking',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36'
}

url = "https://www.thebankerdatabase.com/index.cfm/search/index.cfm"
params = {
    'fuseaction': 'search.search_results_json',
    'ajax': '1',
    'ranking': '1',
}
payload = {
    'draw': '4',
    'columns[0][data]': 'bank_id',
    'columns[0][name]': 'bank_id',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'primary_ranking',
    'columns[1][name]': 'primary_ranking',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': '1',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'previous_ranking',
    'columns[2][name]': 'previous_ranking',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': '1',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'current_name',
    'columns[3][name]': 'current_name',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': '1',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'country_name',
    'columns[4][name]': 'country_name',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': '1',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'yearend_datetime',
    'columns[5][name]': 'yearend_datetime',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': '1',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'DP2',
    'columns[6][name]': 'DP2',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': '1',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'DP2_change',
    'columns[7][name]': 'DP2_change',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': '1',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'DP2_rank',
    'columns[8][name]': 'DP2_rank',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': '1',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'DP6',
    'columns[9][name]': 'DP6',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': '1',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'DP6_change',
    'columns[10][name]': 'DP6_change',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': '1',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'DP6_rank',
    'columns[11][name]': 'DP6_rank',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': '1',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'DP1',
    'columns[12][name]': 'DP1',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': '1',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'DP1_change',
    'columns[13][name]': 'DP1_change',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': '1',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'DP12',
    'columns[14][name]': 'DP12',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': '1',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'DP48',
    'columns[15][name]': 'DP48',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': '1',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'DP48_rank',
    'columns[16][name]': 'DP48_rank',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': '1',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'columns[17][data]': 'DP130',
    'columns[17][name]': 'DP130',
    'columns[17][searchable]': 'true',
    'columns[17][orderable]': '1',
    'columns[17][search][value]': '',
    'columns[17][search][regex]': 'false',
    'columns[18][data]': 'DP130_rank',
    'columns[18][name]': 'DP130_rank',
    'columns[18][searchable]': 'true',
    'columns[18][orderable]': '1',
    'columns[18][search][value]': '',
    'columns[18][search][regex]': 'false',
    'columns[19][data]': 'DP13',
    'columns[19][name]': 'DP13',
    'columns[19][searchable]': 'true',
    'columns[19][orderable]': '1',
    'columns[19][search][value]': '',
    'columns[19][search][regex]': 'false',
    'columns[20][data]': 'DP13_rank',
    'columns[20][name]': 'DP13_rank',
    'columns[20][searchable]': 'true',
    'columns[20][orderable]': '1',
    'columns[20][search][value]': '',
    'columns[20][search][regex]': 'false',
    'columns[21][data]': 'DP8',
    'columns[21][name]': 'DP8',
    'columns[21][searchable]': 'true',
    'columns[21][orderable]': '1',
    'columns[21][search][value]': '',
    'columns[21][search][regex]': 'false',
    'columns[22][data]': 'DP49',
    'columns[22][name]': 'DP49',
    'columns[22][searchable]': 'true',
    'columns[22][orderable]': '1',
    'columns[22][search][value]': '',
    'columns[22][search][regex]': 'false',
    'columns[23][data]': 'DP49_rank',
    'columns[23][name]': 'DP49_rank',
    'columns[23][searchable]': 'true',
    'columns[23][orderable]': '1',
    'columns[23][search][value]': '',
    'columns[23][search][regex]': 'false',
    'columns[24][data]': 'DP131',
    'columns[24][name]': 'DP131',
    'columns[24][searchable]': 'true',
    'columns[24][orderable]': '1',
    'columns[24][search][value]': '',
    'columns[24][search][regex]': 'false',
    'columns[25][data]': 'DP132',
    'columns[25][name]': 'DP132',
    'columns[25][searchable]': 'true',
    'columns[25][orderable]': '1',
    'columns[25][search][value]': '',
    'columns[25][search][regex]': 'false',
    'order[0][column]': '0',
    'order[0][dir]': 'asc',
    'start': '0',
    'length': '100',
    'search[value]': '',
    'search[regex]': 'false',
}
r = requests.post(url, params=params, json=payload, headers=headers)
r.url
r.text
r.json()
