# Configuration file for the Sphinx documentation builder.
# sphinx-build -b html . build
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import ast
import re
from datetime import datetime


def get_version_string():
    """
    get the version of akshare
    :return: version number
    :rtype: str, e.g. '0.6.24'
    """
    with open("../akshare/_version.py", "rb") as _f:
        version_line = re.search(
            pattern=r"__version__\s+=\s+(.*)", string=_f.read().decode("utf-8")
        ).group(1)
        return str(ast.literal_eval(version_line))


latex_engine = "xelatex"
latex_use_xindy = False
latex_elements = {
    "preamble": "\\usepackage[UTF8]{ctex}\n",
}

# myst_parser 会自行注册 .md 解析器，无需 source_parsers（该配置项在新版 Sphinx 已移除）。
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- Project information -----------------------------------------------------

project = "AKShare"
copyright = f"2019–{datetime.now().year}, AKShare Developers"
author = "Albert King"
version = get_version_string()

templates_path = ["_templates"]

# The full version, including alpha/beta/rc tags
release = get_version_string()

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# 不再需要 sphinx_markdown_tables：它当年存在的唯一理由是 recommonmark 不支持
# Markdown 表格，而 myst_parser 原生渲染 GFM 表格（本文档有 16000+ 行表格）。
extensions = ["myst_parser", "sphinx_rtd_theme"]

# Add any paths that contain templates here, relative to this directory.


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "**.ipynb_checkpoints"]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".


master_doc = "index"

# 原先的 setup() 只做两件 recommonmark 专属的事，迁移后都不需要：
# url_resolver 指向 recommonmark 自己的仓库、与本项目无关；
# auto_toc_tree_section = "Contents" 依赖名为 Contents 的小节，
# 而全库 46 个 md 文件中没有任何一个含该小节，属于从未生效的死配置。
#
# myst_parser 默认只启用 CommonMark 加表格。本文档正文中大量出现
# 未转义的下划线与星号（接口名如 stock_zh_a_hist），因此刻意不开启
# 额外的行内语法扩展，避免把接口名误解析为强调。
myst_heading_anchors = 3
